const getRelativeDate = (
  daysOffset: number,
  hours: number,
  minutes: number
) => {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + daysOffset);
  date.setHours(hours, minutes, 0, 0);
  return date;
};

export const sampleResources = [
  {
    id: "1",
    name: "John Doe",
    role: "Frontend Developer",
    department: "Engineering",
    events: [
      {
        id: "e1",
        startDate: getRelativeDate(0, 9, 0),
        endDate: getRelativeDate(0, 10, 30),
        title: "Daily Standup",
        color: "#3b82f6",
        description: "Team daily sync meeting",
      },
      {
        id: "e2",
        startDate: getRelativeDate(0, 14, 0),
        endDate: getRelativeDate(0, 15, 30),
        title: "React Component Review",
        color: "#3b82f6",
        description: "Code review for new components",
      },
      {
        id: "e3",
        startDate: getRelativeDate(2, 11, 0),
        endDate: getRelativeDate(2, 12, 30),
        title: "Frontend Architecture",
        color: "#3b82f6",
        description: "Planning session for new features",
      },
    ],
  },
  {
    id: "2",
    name: "Jane Smith",
    role: "UX Designer",
    department: "Design",
    events: [
      {
        id: "e4",
        startDate: getRelativeDate(0, 13, 0),
        endDate: getRelativeDate(0, 15, 0),
        title: "User Research Session",
        color: "#8b5cf6",
        description: "User testing for new interface",
      },
      {
        id: "e5",
        startDate: getRelativeDate(1, 10, 0),
        endDate: getRelativeDate(1, 12, 0),
        title: "Design Workshop",
        color: "#8b5cf6",
        description: "New feature design brainstorming",
      },
      {
        id: "e6",
        startDate: getRelativeDate(3, 14, 0),
        endDate: getRelativeDate(3, 16, 0),
        title: "Prototype Review",
        color: "#8b5cf6",
        description: "Review interactive prototypes with team",
      },
    ],
  },
  {
    id: "3",
    name: "Mike Johnson",
    role: "Backend Developer",
    department: "Engineering",
    events: [
      {
        id: "e7",
        startDate: getRelativeDate(1, 10, 0),
        endDate: getRelativeDate(1, 12, 30),
        title: "API Development",
        color: "#ef4444",
        description: "New endpoints implementation",
      },
      {
        id: "e8",
        startDate: getRelativeDate(2, 14, 0),
        endDate: getRelativeDate(2, 16, 0),
        title: "Database Optimization",
        color: "#ef4444",
        description: "Performance tuning session",
      },
    ],
  },
  {
    id: "4",
    name: "Sarah Wilson",
    role: "Project Manager",
    department: "Management",
    events: [
      {
        id: "e9",
        startDate: getRelativeDate(2, 14, 0),
        endDate: getRelativeDate(2, 16, 0),
        title: "Client Demo",
        color: "#ec4899",
        description: "Quarterly review with client",
      },
      {
        id: "e10",
        startDate: getRelativeDate(0, 16, 0),
        endDate: getRelativeDate(0, 17, 0),
        title: "Project Planning",
        color: "#ec4899",
        description: "Sprint planning and resource allocation",
      },
    ],
  },
  {
    id: "5",
    name: "David Chen",
    role: "Full Stack Developer",
    department: "Engineering",
    events: [
      {
        id: "e11",
        startDate: getRelativeDate(1, 9, 0),
        endDate: getRelativeDate(1, 11, 0),
        title: "Feature Implementation",
        color: "#10b981",
        description: "Working on user dashboard",
      },
      {
        id: "e12",
        startDate: getRelativeDate(3, 13, 0),
        endDate: getRelativeDate(3, 15, 0),
        title: "Integration Testing",
        color: "#10b981",
        description: "End-to-end testing session",
      },
    ],
  },
  {
    id: "6",
    name: "Emily Rodriguez",
    role: "QA Engineer",
    department: "Quality Assurance",
    events: [
      {
        id: "e13",
        startDate: getRelativeDate(0, 11, 0),
        endDate: getRelativeDate(0, 13, 0),
        title: "Test Case Review",
        color: "#f59e0b",
        description: "Reviewing test scenarios for new release",
      },
      {
        id: "e14",
        startDate: getRelativeDate(2, 10, 0),
        endDate: getRelativeDate(2, 12, 0),
        title: "Automation Scripting",
        color: "#f59e0b",
        description: "Writing automated test scripts",
      },
      {
        id: "e15",
        startDate: getRelativeDate(4, 14, 0),
        endDate: getRelativeDate(4, 16, 0),
        title: "Bug Triage",
        color: "#f59e0b",
        description: "Priority assessment of current issues",
      },
    ],
  },
  {
    id: "7",
    name: "Alex Thompson",
    role: "DevOps Engineer",
    department: "Engineering",
    events: [
      {
        id: "e16",
        startDate: getRelativeDate(1, 14, 0),
        endDate: getRelativeDate(1, 16, 0),
        title: "Infrastructure Deployment",
        color: "#06b6d4",
        description: "Deploying new staging environment",
      },
      {
        id: "e17",
        startDate: getRelativeDate(3, 9, 0),
        endDate: getRelativeDate(3, 11, 0),
        title: "Monitoring Setup",
        color: "#06b6d4",
        description: "Configuring application monitoring",
      },
    ],
  },
  {
    id: "8",
    name: "Lisa Wang",
    role: "Product Manager",
    department: "Product",
    events: [
      {
        id: "e18",
        startDate: getRelativeDate(0, 10, 0),
        endDate: getRelativeDate(0, 11, 30),
        title: "Product Roadmap",
        color: "#84cc16",
        description: "Quarterly roadmap planning session",
      },
      {
        id: "e19",
        startDate: getRelativeDate(2, 13, 0),
        endDate: getRelativeDate(2, 15, 0),
        title: "Stakeholder Meeting",
        color: "#84cc16",
        description: "Update meeting with stakeholders",
      },
      {
        id: "e20",
        startDate: getRelativeDate(4, 9, 0),
        endDate: getRelativeDate(4, 10, 30),
        title: "User Feedback Review",
        color: "#84cc16",
        description: "Analyzing recent user feedback",
      },
    ],
  },
  {
    id: "9",
    name: "Marcus Brown",
    role: "Mobile Developer",
    department: "Engineering",
    events: [
      {
        id: "e21",
        startDate: getRelativeDate(1, 13, 0),
        endDate: getRelativeDate(1, 15, 0),
        title: "iOS App Update",
        color: "#d946ef",
        description: "Working on new mobile features",
      },
      {
        id: "e22",
        startDate: getRelativeDate(3, 10, 0),
        endDate: getRelativeDate(3, 12, 0),
        title: "Cross-platform Sync",
        color: "#d946ef",
        description: "Implementing sync across platforms",
      },
    ],
  },
  {
    id: "10",
    name: "Rachel Green",
    role: "Data Analyst",
    department: "Analytics",
    events: [
      {
        id: "e23",
        startDate: getRelativeDate(0, 14, 0),
        endDate: getRelativeDate(0, 16, 0),
        title: "Data Analysis",
        color: "#f97316",
        description: "Analyzing user behavior metrics",
      },
      {
        id: "e24",
        startDate: getRelativeDate(2, 9, 0),
        endDate: getRelativeDate(2, 11, 0),
        title: "Report Generation",
        color: "#f97316",
        description: "Creating monthly performance reports",
      },
      {
        id: "e25",
        startDate: getRelativeDate(4, 13, 0),
        endDate: getRelativeDate(4, 15, 0),
        title: "Dashboard Updates",
        color: "#f97316",
        description: "Updating analytics dashboards",
      },
    ],
  },
  {
    id: "11",
    name: "Kevin Martinez",
    role: "Team Lead",
    department: "Engineering",
    events: [
      {
        id: "e26",
        startDate: getRelativeDate(0, 9, 0),
        endDate: getRelativeDate(0, 9, 30),
        title: "Team Lead Sync",
        color: "#6366f1",
        description: "Cross-team coordination meeting",
      },
      {
        id: "e27",
        startDate: getRelativeDate(1, 16, 0),
        endDate: getRelativeDate(1, 17, 0),
        title: "One-on-One Meetings",
        color: "#6366f1",
        description: "Individual team member check-ins",
      },
    ],
  },
  {
    id: "12",
    name: "Sophia Kim",
    role: "UI/UX Designer",
    department: "Design",
    events: [
      {
        id: "e28",
        startDate: getRelativeDate(1, 13, 0),
        endDate: getRelativeDate(1, 15, 0),
        title: "Design System Update",
        color: "#a855f7",
        description: "Updating design system components",
      },
      {
        id: "e29",
        startDate: getRelativeDate(3, 10, 0),
        endDate: getRelativeDate(3, 12, 0),
        title: "UI Review",
        color: "#a855f7",
        description: "Reviewing new interface designs",
      },
    ],
  },
];